// Code generated by goctl. DO NOT EDIT.
// Source: utils.proto

package server

import (
	"context"

	"github.com/lius-new/blog-backend/rpc/utils/internal/logic"
	"github.com/lius-new/blog-backend/rpc/utils/internal/svc"
	"github.com/lius-new/blog-backend/rpc/utils/utils"
)

type UtilerServer struct {
	svcCtx *svc.ServiceContext
	utils.UnimplementedUtilerServer
}

func NewUtilerServer(svcCtx *svc.ServiceContext) *UtilerServer {
	return &UtilerServer{
		svcCtx: svcCtx,
	}
}

func (s *UtilerServer) MD5(ctx context.Context, in *utils.MD5Reqeust) (*utils.MD5Reponse, error) {
	l := logic.NewMD5Logic(ctx, s.svcCtx)
	return l.MD5(in)
}
