// Code generated by goctl. DO NOT EDIT.
package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

var prefixSecretCacheKey = "cache:secret:"

type secretModel interface {
	Insert(ctx context.Context, data *Secret) (primitive.ObjectID, error)
	FindOne(ctx context.Context, id string) (*Secret, error)
	FindByUID(ctx context.Context, uid string) (*Secret, error)
	Update(ctx context.Context, data *Secret) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
	DeleteByUID(ctx context.Context, uid string) (int64, error) 
}

type defaultSecretModel struct {
	conn *monc.Model
}

func newDefaultSecretModel(conn *monc.Model) *defaultSecretModel {
	return &defaultSecretModel{conn: conn}
}

func (m *defaultSecretModel) Insert(ctx context.Context, data *Secret) (primitive.ObjectID, error) {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixSecretCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return data.ID,err
}

func (m *defaultSecretModel) FindOne(ctx context.Context, id string) (*Secret, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Secret
	key := prefixSecretCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultSecretModel) FindByUID(ctx context.Context, uid string) (*Secret, error) {
	var data Secret
	err := m.conn.FindOneNoCache(ctx, &data, bson.M{"userId": uid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultSecretModel) Update(ctx context.Context, data *Secret) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()
	key := prefixSecretCacheKey + data.ID.Hex()
	res, err := m.conn.UpdateOne(ctx, key, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultSecretModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}
	key := prefixSecretCacheKey + id
	res, err := m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return res, err
}

func (m *defaultSecretModel) DeleteByUID(ctx context.Context, uid string) (int64, error) {
	res, err := m.conn.DeleteMany(ctx, bson.M{"userId": uid})
	return res, err
}
