// Code generated by goctl. DO NOT EDIT.
package types

type UserBackend struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Status   bool   `json:"status"`
}

type CreateRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type CreateResponse struct {
	Data   UserBackend `json:"data"`
	Status bool        `json:"status"`
}

type DeleteResponse struct {
	Id     string `json:"id"`
	Status bool   `json:"status"`
}

type IdRequest struct {
	Id string `path:"id"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type ModifyRequest struct {
	Id       string `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Status   bool   `json:"status"`
}

type SelectPage struct {
	PageNum  int64 `json:"page_num"`
	PageSize int64 `json:"page_size"`
}

type SelectPageResponse struct {
	Data   []UserBackend `json:"data"`
	Status bool          `json:"status"`
}
