// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/lius-new/blog-backend/api/article/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: GetArticlesInFrontendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: GetArticleInFrontendHandler(serverCtx),
			},
		},
		rest.WithPrefix("/articles"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:id/auth",
					Handler: GetArticleInBackendHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id/auth",
					Handler: DeleteArticlesInBackendHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/auth",
					Handler: GetArticlesInBackendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth",
					Handler: CreateArticlesInBackendHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/auth",
					Handler: ModifyArticlesInBackendHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/articles"),
	)
}
