// Code generated by goctl. DO NOT EDIT.
package types

type Article struct {
	Id          string   `json:"id"`          // 文章id
	Title       string   `json:"title"`       // 文章标题
	Description string   `json:"description"` // 文章描述
	Tags        []string `json:"tags"`        // 文章tag
	UpdateAt    int64    `json:"updateAt"`    // 文章更新时间
}

type Data struct {
	Id          string   `json:"id"`         // 文章id
	Title       string   `json:"title"`      // 文章标题
	Content     string   `json:"content"`    // 文章内容
	Description string   `json:"descritipn"` // 文章描述
	Tags        []string `json:"tags"`       // 文章tag
	Covers      []string `json:"covers"`     // 文章Cover图片
	Visiable    bool     `json:"visiable"`   // 文章状态
	CreateAt    int64    `json:"createAt"`   // 文章创建时间
	UpdateAt    int64    `json:"updateAt"`   // 文章更新时间
	DeleteAt    int64    `json:"deleteAt"`   // 删除更新时间
}

type CreateArticleRequest struct {
	Title       string   `json:"title"`      // 文章标题
	Content     string   `json:"content"`    // 文章内容
	Description string   `json:"descritipn"` // 文章描述
	Tags        []string `json:"tags"`       // 文章tag
	Covers      []string `json:"covers"`     // 文章Cover图片
	Visiable    bool     `json:"visiable"`   // 文章状态
}

type CreateArticleResponse struct {
}

type DeleteArticleRequest struct {
	Id string `json:"id"` // 文章id
}

type DeleteArticleResponse struct {
	Id string `json:"id"` // 文章id
}

type GetArticleByIdWithBackendRequest struct {
	Id string `json:"id"` // 文章id
}

type GetArticleByIdWithBackendResponse struct {
	Data Data `json:"data"`
}

type GetArticleByIdWithViewRequest struct {
	Id string `json:"id"` // 文章id
}

type GetArticleByIdWithViewResponse struct {
	Id          string   `json:"id"`          // 文章id
	Title       string   `json:"title"`       // 文章标题
	Description string   `json:"description"` // 文章描述
	Content     string   `json:"content"`     // 文章内容
	Tags        []string `json:"tags"`        // 文章tag
	Covers      []string `json:"covers"`      // 文章tag
	UpdateAt    int64    `json:"updateAt"`    // 文章更新时间
}

type GetArticleByPageWithViewRequest struct {
	PageNum  int64 `json:"page_num"`  // 多少页
	PageSize int64 `json:"page_size"` // 每页多少条数据
}

type GetArticleByPageWithViewResponse struct {
	Data  []Article `json:"data"` // 当前页的文章数据
	Total int64     `json:"total"`
}

type GetArticleByTagNameWithBackendRequest struct {
	TagName  string `json:"tag_name"`  // 标签name
	PageNum  int64  `json:"page_num"`  // 多少页
	PageSize int64  `json:"page_size"` // 每页多少条数据
}

type GetArticleByTagNameWithBackendResponse struct {
	Data  []Data `json:"data"` // 当前页的文章数据
	Total int64  `json:"total"`
}

type GetArticleByTagNameWithViewRequest struct {
	TagName  string `json:"tag_name"`  // 标签name
	PageNum  int64  `json:"page_num"`  // 多少页
	PageSize int64  `json:"page_size"` // 每页多少条数据
}

type GetArticleByTagNameWithViewResponse struct {
	Data  []Article `json:"data"` // 当前页的文章数据
	Total int64     `json:"total"`
}

type GetArticlesByPageWithBackendRequest struct {
	PageNum  int64 `json:"page_num"`  // 多少页
	PageSize int64 `json:"page_size"` // 每页多少条数据
}

type GetArticlesByPageWithBackendResponse struct {
	Data  []Data `json:"data"`
	Total int64  `json:"total"`
}

type ModifyArticleContentRequest struct {
	Id      string `json:"id"`      // 文章id
	Content string `json:"content"` // 文章id
}

type ModifyArticleContentResponse struct {
}

type ModifyArticleCoverRequest struct {
	Id     string   `json:"id"`     // 文章id
	Covers []string `json:"covers"` // 文章id
}

type ModifyArticleCoverResponse struct {
}

type ModifyArticleDescRequest struct {
	Id   string `json:"id"`   // 文章id
	Desc string `json:"desc"` // 文章id
}

type ModifyArticleDescResponse struct {
}

type ModifyArticleTagRequest struct {
	Id   string   `json:"id"`   // 文章id
	Tags []string `json:"tags"` // 文章id
}

type ModifyArticleTagResponse struct {
}

type ModifyArticleTitleRequest struct {
	Id    string `json:"id"`    // 文章id
	Title string `json:"title"` // 文章id
}

type ModifyArticleTitleResponse struct {
}

type ModifyArticleVisiableRequest struct {
	Id       string `json:"id"`       // 文章id
	Visiable bool   `json:"visiable"` // 文章id
}

type ModifyArticleVisiableResponse struct {
}

type SearchArticleRequest struct {
	Search string `path:"search"` // 搜素内容: 标题, 描述, 内容
}

type SearchArticleResponse struct {
	Data  []Article `json:"data"` // 当前页的文章数据
	Total int64     `json:"total"`
}
