// Code generated by goctl. DO NOT EDIT.
package types

type Article struct {
	Id          string   `json:"id"`          // 文章id
	Title       string   `json:"title"`       // 文章标题
	Description string   `json:"description"` // 文章描述
	Tags        []string `json:"tags"`        // 文章tag
	UpdateAt    int64    `json:"updateAt"`    // 文章更新时间
}

type ArticleBackend struct {
	Id          string   `json:"id"`         // 文章id
	Title       string   `json:"title"`      // 文章标题
	Content     string   `json:"content"`    // 文章内容
	Description string   `json:"descritipn"` // 文章描述
	Tags        []string `json:"tags"`       // 文章tag
	Covers      []string `json:"covers"`     // 文章Cover图片
	Status      bool     `json:"status"`     // 文章状态
	CreateAt    int64    `json:"createAt"`   // 文章创建时间
	UpdateAt    int64    `json:"updateAt"`   // 文章更新时间
	DeleteAt    int64    `json:"deleteAt"`   // 删除更新时间
}

type ReqInBackend struct {
	Id          string   `json:"id"`         // 文章id
	Title       string   `json:"title"`      // 文章标题
	Content     string   `json:"content"`    // 文章内容
	Description string   `json:"descritipn"` // 文章描述
	Tags        []string `json:"tags"`       // 文章tag
	Covers      []string `json:"covers"`     // 文章Cover图片
	Status      bool     `json:"status"`     // 文章状态
}

type RespInBackend struct {
	Data   ArticleBackend `json:"data"`
	Status bool           `json:"status"`
}

type ViewsReq struct {
	PageNum  int `json:"page_num"`  // 多少页
	PageSize int `json:"page_size"` // 每页多少条数据
}

type ViewsResp struct {
	Data   []Article `json:"data"`   // 当前页的文章数据
	Status bool      `json:"status"` // 是否访问成功
}

type ViewsRespInBackend struct {
	Data   []ArticleBackend `json:"data"`
	Status bool             `json:"status"`
}
