// Code generated by goctl. DO NOT EDIT.
// Source: analyzer.proto

package server

import (
	"context"

	"github.com/lius-new/blog-backend/rpc/analyzer/analyzer"
	"github.com/lius-new/blog-backend/rpc/analyzer/internal/logic"
	"github.com/lius-new/blog-backend/rpc/analyzer/internal/svc"
)

type AnalyzerServer struct {
	svcCtx *svc.ServiceContext
	analyzer.UnimplementedAnalyzerServer
}

func NewAnalyzerServer(svcCtx *svc.ServiceContext) *AnalyzerServer {
	return &AnalyzerServer{
		svcCtx: svcCtx,
	}
}

func (s *AnalyzerServer) Ping(ctx context.Context, in *analyzer.Request) (*analyzer.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
