// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/lius-new/blog-backend/api/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/users"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/",
					Handler: ModifyUserNameAndPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: CreateHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: SelectByPageHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: DeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: SelectHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/password",
					Handler: ModifyPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/secret",
					Handler: ModifyRefreshSecretHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/status",
					Handler: ModifyStatusHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/username",
					Handler: ModifyUserNameHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/users"),
	)
}
